/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function runCommitWizardCli(argv: string[]): Promise<NapiResult>
export declare function sum(a: number, b: number): number
