name: build & release

on:
  push:
    branches:
      - main
      - feature/*
      # NOTE: Removed tag triggers to prevent duplicate runs
      # Tag-triggered releases are now handled by release.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  # Use the reusable workflow for build and test validation
  # This workflow now focuses on CI validation only
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      upload_artifacts: false  # CI validation doesn't need artifacts
      run_coverage: true       # Generate coverage for branch/PR feedback

  # NOTE: Publishing is now handled by the dedicated release.yml workflow
  # which is triggered only by tag pushes, eliminating duplicate runs