name: CI

on:
  push:
    branches:
      - feature/*
      - develop
      - release/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  # run commitlint on pull requests
  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: install commitlint
        run: npm install conventional-changelog-conventionalcommits @commitlint/config-conventional @commitlint/cli

      - name: lint commits in pr
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  # run build and test validation
  validate:
    uses: ./.github/workflows/common-build.yml
    with:
      upload_artifacts: false  # ci doesn't need artifacts, just validation
      run_coverage: true       # generate coverage for pr feedback