name: Common Build & Test

on:
  workflow_call:
    inputs:
      upload_artifacts:
        description: 'Whether to upload build artifacts'
        required: false
        type: boolean
        default: true
      run_coverage:
        description: 'Whether to run coverage reporting'
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: build - ${{ matrix.settings.target }} (${{ matrix.settings.host }})
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux-x64-gnu
          - host: macos-13
            target: x86_64-apple-darwin
            platform: darwin-x64
          - host: macos-latest
            target: aarch64-apple-darwin
            platform: darwin-arm64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            platform: win32-x64-msvc

    steps:
      - uses: actions/checkout@v4
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: commit-wizard-napi/package-lock.json

      - name: install rust
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}
          components: clippy
      
      - name: cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.settings.target }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: cache cargo tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-audit
            ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-cargo-tools-v2

      - name: install cargo-audit (if not cached)
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          # cross-platform install - cargo install skips if already present
          cargo install cargo-audit --locked || echo "cargo-audit already installed"

      - name: run cargo-audit
        run: |
          # run cargo audit but don't fail on warnings
          cargo audit || true

      - name: run clippy
        run: cargo clippy -- -D warnings

      - name: run cargo tests
        run: cargo test

      - name: install cargo-tarpaulin for coverage (if not cached)
        if: inputs.run_coverage && matrix.settings.host == 'ubuntu-latest' && steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          # cross-platform install - cargo install skips if already present
          cargo install cargo-tarpaulin --locked || echo "cargo-tarpaulin already installed"

      - name: run coverage
        if: inputs.run_coverage && matrix.settings.host == 'ubuntu-latest'
        run: cargo tarpaulin --all-features --workspace --exclude commit-wizard-napi --out Html --out Json

      - name: upload coverage report
        if: inputs.run_coverage && matrix.settings.host == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            tarpaulin-report.html
            tarpaulin-report.json

      - name: add coverage summary
        if: inputs.run_coverage && matrix.settings.host == 'ubuntu-latest'
        run: |
          echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          
          # extract coverage percentage from json
          if [ -f tarpaulin-report.json ]; then
            COVERAGE=$(cat tarpaulin-report.json | grep -o '"coverage":[0-9.]*' | cut -d':' -f2)
            if [ ! -z "$COVERAGE" ]; then
              COVERAGE_PERCENT=$(echo "$COVERAGE * 100" | bc -l | cut -d'.' -f1)
              echo "Overall coverage: **${COVERAGE_PERCENT}%**" >> $GITHUB_STEP_SUMMARY
              
              # add coverage badge colour
              if [ "$COVERAGE_PERCENT" -ge 80 ]; then
                echo "🟢 Good coverage" >> $GITHUB_STEP_SUMMARY
              elif [ "$COVERAGE_PERCENT" -ge 60 ]; then
                echo "🟡 Moderate coverage" >> $GITHUB_STEP_SUMMARY
              else
                echo "🔴 Low coverage" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Full HTML report available in artifacts." >> $GITHUB_STEP_SUMMARY
      
      - name: build napi module
        shell: bash
        run: |
          cd commit-wizard-napi
          npm install
          npm run build
          npm test
          ls -la
          find . -name "*.node" -type f
      
      - name: build rust cli binary
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.settings.target }} --bin commit-wizard
          
          # prepare binary with appropriate extension
          if [[ "${{ matrix.settings.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.settings.target }}/release/commit-wizard.exe commit-wizard-${{ matrix.settings.target }}.exe
          else
            cp target/${{ matrix.settings.target }}/release/commit-wizard commit-wizard-${{ matrix.settings.target }}
          fi
      
      - name: upload napi artifacts
        if: inputs.upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.platform }}
          path: commit-wizard-napi/*.node
          if-no-files-found: error
      
      - name: upload rust binary artifacts
        if: inputs.upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-binary-${{ matrix.settings.target }}
          path: commit-wizard-${{ matrix.settings.target }}*
          if-no-files-found: error