name: lint commits

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install commitlint
        run: npm install conventional-changelog-conventionalcommits @commitlint/config-conventional @commitlint/cli

      - name: lint commits in pr
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose 