name: lint commits

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: install commitlint
        run: npm install conventional-changelog-conventionalcommits @commitlint/config-conventional @commitlint/cli

      - name: lint commits in pr
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose 