name: prepare release

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  prepare:
    name: prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing commits and tags

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for analysing commits

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: configure git user
        run: |
          git config --global user.name "jamie"
          git config --global user.email "jamie@prettypragmatic.com"

      - name: run release tool
        id: run_release_tool
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Running release tool for main branch..."
          
          # get commit hash before running release-tool
          BEFORE_COMMIT=$(git rev-parse HEAD)
          
          if ! cargo run --bin release-tool; then
            echo "::error::Release tool failed on main branch"
            exit 1
          fi
          echo "Release tool completed successfully"
          
          # check if release-tool created a new commit
          AFTER_COMMIT=$(git rev-parse HEAD)
          if [[ "$BEFORE_COMMIT" != "$AFTER_COMMIT" ]]; then
            echo "Release tool created new commit: $AFTER_COMMIT"
            echo "release_created=true" >> $GITHUB_OUTPUT
          else
            echo "No release created (no releasable changes detected)"
            echo "release_created=false" >> $GITHUB_OUTPUT
          fi

      - name: run release tool (dry run)
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          echo "Running release tool dry run for release branch..."
          if ! cargo run --bin release-tool -- --dry-run; then
            echo "::error::Release tool dry run failed"
            exit 1
          fi
          echo "Release tool dry run completed successfully"

      - name: push changes and tags
        if: steps.run_release_tool.outputs.release_created == 'true'
        run: |
          echo "Pushing release commit and tags..."
          git push origin HEAD
          git push origin --tags
          echo "Successfully pushed release commit and tags" 