name: prepare release

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  prepare:
    name: prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing commits and tags

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for analysing commits

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: run release tool
        run: cargo run --bin release-tool

      - name: push changes and tags
        run: |
          git push origin HEAD:main
          git push origin --tags 