name: prepare release

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  prepare:
    name: prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing commits and tags

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for analysing commits

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: configure git user
        run: |
          git config --global user.name "jamie"
          git config --global user.email "jamie@prettypragmatic.com"

      - name: run release tool
        if: github.ref == 'refs/heads/main'
        run: cargo run --bin release-tool

      - name: run release tool (dry run)
        if: startsWith(github.ref, 'refs/heads/release/')
        run: cargo run --bin release-tool -- --dry-run

      - name: push changes and tags
        run: |
          git push origin HEAD:main
          git push origin --tags 