name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up rust
        uses: dtolnay/rust-toolchain@stable
      - name: build crates
        run: cargo build --release --workspace
      # placeholder: upload artifacts, build napi modules, etc.

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
      # placeholder: download artifacts and publish crates and npm packages
      - name: publish dry run (todo)
        run: echo "publishing packages..." 